### ISSUE TITLE
Add documentation for Google APIs that have to be enabled

### ISSUE THREAD

**Issue by jeverling** [erdem/django-map-widgets#115]
It took me a bit to figure out that I had to enable the Places API. It's obvious in hindsight, but it might be helpful to others to list all Google APIs that this package uses.

And thank you very much for this project, it is a great time-saver!

**Comment by andrewsiah** [comment]
Hi jeverling! Great to hear that it worked for you. 

Wondering if you'll be able to help me. In my forms.py, I get a "NameError: name 'City' is not defined". I believe it's to do with the fact that I haven't imported the City model from anywhere into the forms.py yet. Wonder if you can help.

Thanks a lot :)
<img width="760" alt="Screenshot 2020-12-28 at 3 31 07 PM" src="https://user-images.githubusercontent.com/31041391/103197805-b5eeb300-4921-11eb-9ad5-494466ce96c7.png">

<img width="584" alt="Screenshot 2020-12-28 at 3 31 17 PM" src="https://user-images.githubusercontent.com/31041391/103197823-bbe49400-4921-11eb-827c-9c11f03b7275.png">

**Comment by jeverling** [comment]
Hi Andrew, I think you just have to add , `City` to this line:

`from .models import Job, User, Category, Application, Jobber`

Unless the `City` model is defined somewhere else than in `jobber/models.py`.
Hope you get it working.

**Comment by andrewsiah** [comment]
Thanks for the swift reply!

Am sure glad you pointed out the demo, I jumped straight into the documentation and didn't notice it. 

Btw, would we need to use PostgreSQL instead of the standard SQLite as the default database for our django project instead? (I noticed the demo provided used PostgreSQL instead of my SQLite.) Thus subsequently installing PostGIS and all its dependencies [as guided here](https://docs.djangoproject.com/en/3.1/ref/contrib/gis/install/postgis/)??
<img width="629" alt="Screenshot 2020-12-28 at 8 33 35 PM" src="https://user-images.githubusercontent.com/31041391/103214646-f6fbbd00-494b-11eb-8c23-b483441c1582.png">

Also, mind sharing what django version you're used this on? Just hoping that this package still works on django 3.1.4.

**Comment by jeverling** [comment]
Yes, you actually need PostGIS (vanilla PostgreSQL is not enough).
I just run a Docker container like this:

`docker run --name postgis_db -e POSTGRES_PASSWORD=your_password -e POSTGRES_DB=your_db -v /opt/docker/volumes/some_volume_name/data:/var/lib/postgresql/data -p 5432:5432 -d postgis/postgis`

Due to the port forwarding, you can then just use `localhost` as `HOST`.

**Comment by erdem** [comment]
@jeverling Thank you for your contributions! 

When I was documenting this package usage in the first place, Google Map APIs configuration page was so different. I saw the entire page has changed after reading your message. Also, as far as I remember only Google Map JS API activation was enough to use the widget. However, I have added new `Google APIs configuration` sections to each widget documents. Also, this issue gave me a chance to test map widgets on Django 3.1, they work fine. 

https://django-map-widgets.readthedocs.io/en/latest/widgets/point_field_map_widgets.html
