### ISSUE TITLE
how can I change the template of form column?

### ISSUE THREAD

**Issue by yuwin** [erdem/django-map-widgets#118]
Hi, I would like to create a django form with a location field(column). I put the widget in to my own template, but when it comes to mobile display, the search bar seem not auto fit with my page. 

I would like to know, is it possible to modify the template of it? thanks

<img width="513" alt="截圖 2021-02-13 下午9 57 21" src="https://user-images.githubusercontent.com/6879200/107851757-307a8000-6e47-11eb-870d-c19ea2dd37ef.png">

**Comment by erdem** [comment]
Hi @yuwin  

In order to override the widget template, you can set the widget `template_name` with your custom widget class implementation. 


```python
from mapwidgets.widgets import GooglePointFieldWidget

class CustomGooglePointFieldWidget(GooglePointFieldWidget):
    template_name = 'custom-widget.html'


class CityCreateForm(forms.ModelForm):

    class Meta:
        model = City
        fields = ('name', 'location')
        widgets = {
            'location': CustomGooglePointFieldWidget,
        }

```


https://github.com/erdem/django-map-widgets/blob/master/mapwidgets/templates/mapwidgets/google-point-field-widget.html

Besides, you can extend the base widget template to template customization.
