### ISSUE TITLE
Help request: Create javascript event listener

### ISSUE THREAD

**Issue by ShmuelTreiger** [erdem/django-map-widgets#152]
Hi!
I'm trying to create an event listener for the djange-map-widget. I've tried the following ways, none of which as worked:

```
            document.getElementById("id_address_point").addEventListener("change", updateFakePoint);
            document.getElementById("id_address_point").addEventListener("leafletPointFieldWidget:markerChange", updateFakePoint);
        
            (function ($) {
                $(document).on("leafletPointFieldWidget:markerChange", updateFakePoint);
            })(jQuery)
```

I also tried just
```
        (function ($) {
            $(document).on("leafletPointFieldWidget:markerChange", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log(locationInputElem); // Django widget textarea widget (hidden)
                console.log(lat, lng);  // Changed marker coordinates
                console.log(mapWrapID); // Map widget wrapper element ID
            });
        })(jQuery)
```
And nothing prints to console.

In my head I have:
`    <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"></script>`

When I update id_address_point, updateFakePoint doesn't trigger. Would appreciate recommendation on how I can do this correctly. Thank you!

**Comment by erdem** [comment]
Hi @ShmuelTreiger 

Unfortunately, those event triggers are not available for the Leaflet interactive widget. It was my copy-paste mistake that added the wrong info to the widget documentation. I have just pushed a commit to main to update the widget documentation.

However, you can catch those events with Leaflet instance map objects which are bound to the map HTML element data [here](https://github.com/erdem/django-map-widgets/blob/d7b390c55a9e3787b4449f4db0e249d715011ea5/mapwidgets/static/mapwidgets/js/pointfield/interactive/leaflet/mw_pointfield.js#L15).

```javascript
// HTML element given by id string formatting, "<field_name>-map-elem". My demo model field name is `location`.

(function ($) {
    $("#location-map-elem").data("mwMapObj"); // Leaflet map object
    $("#location-map-elem").data("mwClassObj"); // jQuery class implementation object
})(jQuery);

```

Feel free to open a pull request to fix this; otherwise, I will add this feature to the next release. Thanks for the notice.

**Comment by ShmuelTreiger** [comment]
Sorry, I'm not terribly familiar with jQuery. Do you have any idea why this isn't working?

```
            $('#address-point-map-elem').change(function () {
                <function>;
            });
```
I also tried `address_point-map-elem` and `id_address_point`.

**Comment by erdem** [comment]
This is not what I meant, get to know how you can use [jquery data](https://api.jquery.com/data/) in your cases.
