### ISSUE TITLE
zoom settings is not working.

### ISSUE THREAD

**Issue by jlariza** [erdem/django-map-widgets#7]
Hello, 

I have the following settings

`
MAP_WIDGETS = {
    "GooglePointFieldWidget": (
        ("zoom", 0),
    ),
    "GOOGLE_MAP_API_KEY": 'MY-GOOGLE-MAPS-API-KEY'
}
`
however, The zoom parameter is not working. I have change it from 15, to 0 and other values and it keeps rendering the map with the same zoom. Do you know how to make it work?
I have printed the values that the widget gets, and they are correct. The problem seems to be when the js is rendered, apparently it is not getting the zoom value correctly.

Thank you

**Comment by jlariza** [comment]
I found the problem.

At /mapwidgets/static/mapwidgets/js/mw_google_point_field.js line 62 the function "fitBoundMarker" is defined. For some reason, before the function, this.zoom is equals to the value I set in the settings but inside the function this.zoom is always equals to 21. This produce that the following conditional at line 67 is always true, 
`                 if (this.getZoom() > 15) {
                     this.setZoom(15)
                 }
`
setting the map zoom as 15 always, no matter what your original zoom setting was. I fixed it commenting the fitBoundMarker function (the map disappears if the conditional gets commented) ; but I am not sure if it is important and what it is doing. I hope that with this information you are able to fix the error. I think that the zoom checking could be done from python and fix/remove the fitBoundMarker function if it is solely checking bad zoom configurations.

**Comment by erdem** [comment]
Hi Jlariza

I implemented that logic because of when I used google map `fitBounds` support for a single marker, the map zoom value is getting maximum. This is not helping for end users when they are searching specific address. Check the screenshot.

<img width="468" alt="ss" src="https://cloud.githubusercontent.com/assets/1518272/20677054/c501ab2a-b589-11e6-9e64-5166a0a8c4a9.png">

As you can see `Victoria station` doesn't appear on the map at the maximum zoom value. It can be seen decrease the zoom level. The maximum zoom value is not useful for single marker viewing. This is the best solution I found for this user experience issue. 

I think, that zoom logic must be optional. I will add a settings value for the logic.

Of course, we can discuss other solutions for this issue.

Thanks.

**Comment by erdem** [comment]
@jlariza FYI,

I implemented the new config option for this issue in new version. You can set "markerFitZoom" value on your `MAP_WIDGETS` settings.

Check out the new documentation for more detail. 

http://django-map-widgets.readthedocs.io/en/latest/widgets/point_field_map_widgets.html#settings

Thanks
