### ISSUE TITLE
Not rendering new inline maps

### ISSUE THREAD

**Issue by kikeh** [erdem/django-map-widgets#84]
### Issue
The Map Widget Inline does not render while adding a new inline to the form.

### Description
I am using `django-map-widgets` in my Django Admin for storing series of coordinates/positions more easily. The first mandatory point appears automatically while loading the form and its map is loading fine. However, when I click the "Add" button for getting more inlines maps, the form loads but the map is not rendered.

I have noticed that `django-map-widgets` loads a template (`google-point-field-inline-widget.html`) dynamically and that template only contains a `<script type="application/javascript"> ... </script>`, so it looks like it is not running the script when the template loads with the "Add" button.

I find it weird since in the [docs](https://django-map-widgets.readthedocs.io/en/v0.2.0/widgets/point_field_inline_map_widgets.html), the inlines apparently work just fine (as shown in the example), so I do not know what is wrong.

I am using the latest version of both Django (v2.1.2) and django-map-widgets (v0.20.0). I am using Django Suit, but it does not look like it is the problem, since I tried removing it and had the same behavior.

### Workaround
I have created a workaround by adding an extra _js_ file to the admin class, that contains the javascript in the template, but with hardcoded settings, since it is not possible to load them dynamically. But I understand that this is not the expected behavior and would need a better solution.

**Comment by maerzhase** [comment]
having exactly the same issue. happens when using the map widgets in inline admin forms.

**Comment by erdem** [comment]
I spent a couple of hours on this issue, but I can't find a proper solution yet. The main problem is Django Admin loading the `inlines.js` script before the widgets jQuery file, and it can't render the `add more` buttons for inlines. I had explained in @maerzhase PR before. 

https://github.com/erdem/django-map-widgets/pull/92#discussion_r254061468 

The best workaround solution could be adding a new `inlines.js` to widgets static files, but I didn't want to do that because it can raise other issues.
